version: '2'

services:
  wordpress:
    image: wordpress:4.9.3
    container_name: wordpress
    depends_on:
      - mysql
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs7.papertrailapp.com:28447"
        tag: "{{.Name}}/{{.ID}}"

  nginx:
    image: nginx:latest
    container_name: nginx-wordpress
    depends_on:
      - wordpress
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs7.papertrailapp.com:28447"
        tag: "{{.Name}}/{{.ID}}"

  datadog:
    container_name: datadog
    build: datadog
    links:
      - mysql
      - nginx
    environment:
      - DD_API_KEY=<DD_API_KEY>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
